### ISSUE TITLE
Potential registry/QDir issue

### ISSUE THREAD

**Issue by awslattery** [Proj-Ascension/Client#100]
**Description**

> for shits and giggles, I ran this on my work pc where I have neither steam, nor origin, nor uplay installed. The result was two false positives and a subsequent crash of the program.

[reported by /u/rhetoricalkarma](https://www.reddit.com/r/Project_Ascension/comments/3p0cyp/palauncher_windows_78110_download_for_10162015/cw6674o)

**Expected Action**
Not find any directories, as Steam/Origin/uPlay are not installed

**Actual Action**
- Two false positives
- Application crashed

**Steps to Reproduce**
Unknown.

**System**
Windows 10 Pro x64

**Screenshot(s)**
![Screenshot](https://i.imgur.com/eTWhewe.png)

**Comment by Jtramey** [comment]
I am getting a false positive on Mac for Origin but not with steam. Same issue with path being "."

**Comment by elken** [comment]
Fixed in #102
