### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by frederic2ec** [Proj-Ascension/Client#116]
Hi,
I have some error wen I compile on Clion.
Here the log: http://pastebin.com/9S4ExKme

Thank you!

**Comment by lolzballs** [comment]
`dwmapi.h` is a part of the Windows API, and should be provided by your compiler. The Qt MinGW distro works for me, and the MSVC compilers should work as well.

**Comment by frederic2ec** [comment]
I have test the Visual Studio Method but on Cmake Gui I have an little error.
The error:

CMake Error at CMakeLists.txt:11 (project):
  No CMAKE_C_COMPILER could be found.
CMake Error at CMakeLists.txt:11 (project):
  No CMAKE_CXX_COMPILER could be found.

Thank you!
