### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by frederic2ec** [Proj-Ascension/Client#117]
Hi,
I have some little error on CMake Gui when I compile for Visual Studio
The error: 
![ss 2015-12-19 at 07 19 55](https://cloud.githubusercontent.com/assets/1781356/11915806/895c2488-a685-11e5-932f-3867a233cf39.png)
http://pastebin.com/dPBi838C

Thank you!

**Comment by lolzballs** [comment]
Please install MSVC first.

**Comment by frederic2ec** [comment]
I have already installed MSVC.

**Comment by lolzballs** [comment]
First of all, you don't have a msvc 2015 version of Qt installed (it doesn't exist yet). You will need the correct version of MSVC corresponding to the Qt libraries you have installed. The bundled MinGW from Qt should include everything you need.

**Comment by frederic2ec** [comment]
You say I need Visual Studio 2013 and not 2015?

**Comment by elken** [comment]
Yes.

**Comment by frederic2ec** [comment]
Thank you, I will test it
