### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by thomassross** [Proj-Ascension/Client#12]
- Does "ASCENSION" really need to be capitalized?
- Optimally, "Project" and "ascension" would be on the same line
- [The headings](http://puu.sh/hzXjg/48665e0c4b.png) are quite spaced out, maybe make them a bit smaller.

**Comment by Hal9007** [comment]
The current UI is mostly filler and stands only as a working copy for cross-platform efforts. Most of it will change when we get more input from the design team.
