### ISSUE TITLE
Invalid Magic Value

### ISSUE THREAD

**Issue by matjarosz** [Proj-Ascension/Client#120]
Adding Steam games through the wizard shows this error:

> Parsing Steam vdf, located at: "C:/program files (x86)/steam/appcache/appinfo.vdf"
> Invalid magic value!
> The game id: 377160 was not found in the Steam appinfo.vdf.
> QObject::startTimer: Timers can only be used with threads started with QThread

**Comment by elken** [comment]
Problem is with Appveyor, not us.

**Comment by elken** [comment]
_sigh_ turns out this is an msvc bug. For now just use `msvc_workaround.zip`.

**Comment by elken** [comment]
Issue is linked to msvc screwing up endianness.
