### ISSUE TITLE
Database error reported by /u/TIFUbyredditting

### ISSUE THREAD

**Issue by awslattery** [Proj-Ascension/Client#128]
## Bug Description
- A concise description of what the problem is. One sentence will suffice 99% of the time. 
  - Database error on launcher load
  - Source: https://www.reddit.com/r/Project_Ascension/comments/4ci29v/database_error/
## Versions
- Operating System and version
- Project Ascension build number or snapshot version
  - Windows 10
    ##Severity
- Trivial, Minor, Major, or Blocker
  - Major
## Steps to Reproduce
- Step by step instructions on how to reproduce the bug.
- Please be as detailed as you can, we need all of the information we can get. 
  - Unknown, see screenshot below
## Actual Behavior
- Explain what is happening that shouldn't be. Here you can go more in depth than the description. 
  - https://i.imgur.com/PaMR7bk.png
## Expected Behavior
- Explain what _should_ be happening instead of the actual result. 
  - Launcher should launch
## Troubleshooting/Testing Steps Attempted
- What did you do to try and fix it?
  - Prayed to Gaben (no response)
  - Posted to subreddit
## Workaround
- If you found a way to make the program work in spite of the bug, describe how you did it here.
  - Unknown.

**Comment by lolzballs** [comment]
Issue resolved by deleting the ascension.db file.

We may need to look into implementing a "migrations" system for the future.
