### ISSUE TITLE
Native theme

### ISSUE THREAD

**Issue by ScoreUnder** [Proj-Ascension/Client#28]
When this gets off the ground I'd really like to see a native theme. That is, a theme which uses no borderless windows, no draggable areas inside the window, no embedded title bar buttons, and only Qt widgets rather than custom themed ones. I like it when programs "fit in" nicely.

It would also make for a nice 'fallback' theme if the main one can't be used for whatever reason.

**Comment by lolzballs** [comment]
Ultimately, the finished client will be themeable, with the option of just a native theme.

That being said, there still is a lot of planning and work going on in the UI team, and we aren't exactly sure of the UI elements that will be implemented. I can imagine that with the native look, some of the elements would not function properly.

In the end, I believe that if you want the native stuff, go for it, but some of the features will be disabled, like a 'fallback' theme you described.

**Comment by matjarosz** [comment]
We are planning to release our final UI concepts on the beginning of July.
