### ISSUE TITLE
*source games break the steam find code

### ISSUE THREAD

**Issue by elken** [Proj-Ascension/Client#46]
All *source games live in the Half-Life directory & I can't find the manifest listing which directory the game is in. So the choices are:

a) Find the mysterious manifest
b) Use a kv-based STL container to store the sub-directories with their game names and do a lookup.

**Comment by lolzballs** [comment]
Haven't looked into this too much, I presume the locations of the executables can be found inside the appinfo.vdf which has been parsed in #66.

**Comment by elken** [comment]
Probably, yes.

**Comment by elken** [comment]
Fixed in #70.
