### ISSUE TITLE
Better Icons

### ISSUE THREAD

**Issue by lolzballs** [Proj-Ascension/Client#5]
Current icons are pretty blurry. As well, we should standardize on one official logo to use.

**Comment by Lunaari** [comment]
The logo standardization will come when the name is finally decided on. A better set of project_ascension logos can be worked on.

**Comment by glenbaku** [comment]
What size are the icons needed? Do you support vector ones or they need to be .png/.ico?
I'm willing to work with the icons.

**Comment by Hal9007** [comment]
The current icon is pulled locally from a .ico file, so that would be ideal. 256 x 256 px is a fair size.

**Comment by dawid2193487** [comment]
I personally think that vector is the way to go

Also personally: text in ascension_small.png makes it ugly.

**Comment by Hal9007** [comment]
Are we talking about application icons here or just icons within the client? While we will be able to use SVGs for internal images, they're certainly not supported as application icons.

@ca1ek: The images in the resource folder are purely for testing or filler. All of them will be replaced in the future.

**Comment by lolzballs** [comment]
Design is being worked on, and this will come with it.

**Comment by awslattery** [comment]
{ ͡• ͜ʖ ͡•}
