### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by Naruto-kyun** [Proj-Ascension/Client#51]
Hello,

I think you might consider to rewrite your UI in QML while the deadline isn't tomorrow.
This is the future of Qt and you can do more with less code.

Regards,
NK.

**Comment by Hal9007** [comment]
Hey Naruto-kyun,

Thanks for the suggestion. While QML/QtQuick _has_ come quite far in the past few years, it still finds itself more grounded in a lightweight, mobile market. C++ is where Qt continues to find the most modularity, and I don't think it will be forgotten anytime soon. We may consider a few QML interfaces with a C++ functionality layer, but this is unlikely as even the current XML interfaces will probably be scrapped in favor of hardware-accelerated OpenGLWidgets (where we'll have the most control over graphical behavior).

Nevertheless, I don't see it as an additional challenge to modifying or extending the UI at a later date. The team has agreed that there will be an abstracted API to modify each aspect of the interface (currently slated for Boost's Python hooking), to be implemented further down the line.
