### ISSUE TITLE
Add Mozilla Persona

### ISSUE THREAD

**Issue by pizzamaker** [Proj-Ascension/Client#81]
Facebook and Google for signing up is a problem for many, since they are well-known privacy violators.

Please add the Mozilla Persona authentication system: https://developer.mozilla.org/en-US/Persona

**Comment by Jtramey** [comment]
Not Implementing at this time. Login options will be PA account, Google, Facebook, Steam, or a local account option.

**Comment by pizzamaker** [comment]
That's unfortunate. Any specific reason for that decision? ):
