### ISSUE TITLE
Reduce Semaphore Buildtimes

### ISSUE THREAD

**Issue by awslattery** [Proj-Ascension/Client#97]
@elken as you're away for the weekend, when you get a chance, please resolve the dependency issues with Semaphore's build status. We implemented a hot-fix this afternoon to resume passing builds.

**Comment by elken** [comment]
## Semaphore has been shit slow for a while, I will PM the dudes when I can

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by elken** [comment]
_Finally_ got round to talking to the Semaphore guys, apparently Qt was broken in an old version, so they installed new Qt to /opt. Updated the path and we're back to full speed.
